Trigonometric functions
NamorNiradnug/portable-simd-addons pull request #1
Opened 2024-03-09 01:04 UTC by NamorNiradnug

2024-03-19 22:33 UTC, NamorNiradnug commented
Готова вся тригонометрия для `f32`

2024-04-07 20:25 UTC, asokol123 requested changes

2024-04-07 20:25 UTC, asokol123 commented on rust-toolchain.toml
> +channel = "nightly"
Фиксируй конкретный nightly, иначе будет развлечение, когда какие-то фичи/методы удалят/перименуют

2024-04-07 20:25 UTC, asokol123 commented on src/lib.rs
> +#![feature(portable_simd, test, array_chunks)]
А что такое фича test?
Исправлять не надо, просто расскажи)

2024-04-07 20:25 UTC, asokol123 commented on src/math/trig.rs
> +    // These coefficients are not exactly the Taylor expansion but its approximation which
Ссылку на то, откуда взял (код/статья)

2024-04-07 20:25 UTC, asokol123 commented on rust-toolchain.toml
> +channel = "nightly"
А ещё если назвать файл просто rust-toolchain, без .toml, то в него можно просто текстом записать версию и подставлять в GitHub action

2024-04-07 20:25 UTC, asokol123 commented on src/math/f32/trig.rs
> +    // SAFETY: values in `quadrants_float` are finite and between 0 and 1e5
А почему мы знаем что все до 1e5? Строчки выше для меня магия, но вроде ни одна из них ничего такого не делает

2024-04-07 20:31 UTC, NamorNiradnug commented on src/lib.rs
> +#![feature(portable_simd, test, array_chunks)]
Это для #[bench]

2024-04-07 20:32 UTC, NamorNiradnug commented on src/math/f32/trig.rs
> +    // SAFETY: values in `quadrants_float` are finite and between 0 and 1e5
Это из vcl скопирастил, надо разобраться с матчастью

2024-04-12 07:59 UTC, asokol123 approved these changes

2024-04-12 08:01 UTC, merged