Exponent-like functions (`exp`, `exp2`, `exp_m1`)
NamorNiradnug/portable-simd-addons pull request #2
Opened 2024-04-23 14:33 UTC by NamorNiradnug

2024-05-09 07:58 UTC, asokol123 requested changes

2024-05-09 07:58 UTC, asokol123 commented on benches/trig.rs
> +            test::black_box(Simd::from_array(*x).exp());
А тут не надо *x в black_box запихнуть?

2024-05-09 09:04 UTC, NamorNiradnug commented on benches/trig.rs
> +            test::black_box(Simd::from_array(*x).exp());
может и надо, но я бенчмарки в другом pr все равно переделал
но кажется достаточно только самое вернее выражение в `black_box` оборачивать

2024-05-10 08:02 UTC, asokol123 approved these changes

2024-05-11 20:51 UTC, merged